# Generated by Django 4.2.1 on 2023-06-01 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthday_date', models.DateTimeField(verbose_name='birthday date')),
                ('passport_serial', models.CharField(max_length=4)),
                ('passport_number', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('number_rooms', models.IntegerField(max_length=1)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthday_date', models.DateTimeField(verbose_name='birthday date')),
                ('passport_serial', models.CharField(max_length=4)),
                ('passport_number', models.CharField(max_length=6)),
                ('tin', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cost', models.FloatField(max_length=10)),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typeservice')),
            ],
        ),
        migrations.CreateModel(
            name='EntryCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=25)),
                ('create_date', models.DateTimeField(verbose_name='create document date')),
                ('date_arrival', models.DateTimeField(verbose_name='arrival date')),
                ('date_departure', models.DateTimeField(verbose_name='departure date')),
                ('comment', models.IntegerField(max_length=100)),
                ('food', models.CharField(choices=[('food1', 'Первый тмп питания'), ('food2', 'Второй тмп питания'), ('food3', 'Третий тмп питания')], default='food1', max_length=9)),
                ('cost', models.FloatField(max_length=10)),
                ('number_days', models.IntegerField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotelbuilding')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DepartureCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=25)),
                ('create_date', models.DateTimeField(verbose_name='create document date')),
                ('review', models.IntegerField(max_length=100)),
                ('food', models.CharField(choices=[('food1', 'Первый тмп питания'), ('food2', 'Второй тмп питания'), ('food3', 'Третий тмп питания')], default='food1', max_length=9)),
                ('cost_to_deny', models.FloatField(max_length=10)),
                ('days_remaining', models.IntegerField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotelbuilding')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DenyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=25)),
                ('create_date', models.DateTimeField(verbose_name='create document date')),
                ('deny_reason', models.IntegerField(max_length=100)),
                ('food', models.CharField(choices=[('food1', 'Первый тмп питания'), ('food2', 'Второй тмп питания'), ('food3', 'Третий тмп питания')], default='food1', max_length=9)),
                ('cost_to_deny', models.FloatField(max_length=10)),
                ('days_remaining', models.IntegerField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotelbuilding')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
    ]
