# Generated by Django 4.2.1 on 2023-06-01 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_denynumber_deny_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=25)),
                ('create_date', models.DateTimeField(verbose_name='create document date')),
                ('deny_reason', models.CharField(max_length=100)),
                ('food', models.CharField(choices=[('food1', 'Первый тмп питания'), ('food2', 'Второй тмп питания'), ('food3', 'Третий тмп питания')], default='food1', max_length=9)),
                ('cost_to_deny', models.FloatField(max_length=10)),
                ('days_remaining', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotelbuilding')),
            ],
        ),
        migrations.AlterField(
            model_name='entrycustomer',
            name='number_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_rooms',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='DenyNumber',
        ),
        migrations.AddField(
            model_name='denyroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.AddField(
            model_name='denyroom',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
    ]
