# Generated by Django 4.2.1 on 2023-06-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_denyroom_number_alter_entrycustomer_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='denyroom',
            options={'verbose_name': 'Отказ клиента', 'verbose_name_plural': 'Отказы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='departurecustomer',
            options={'verbose_name': 'Выезд клиента', 'verbose_name_plural': 'Выезды клиентов'},
        ),
        migrations.AlterModelOptions(
            name='entrycustomer',
            options={'verbose_name': 'Заезд клиента', 'verbose_name_plural': 'Заезды клиентов'},
        ),
        migrations.AlterModelOptions(
            name='hotelbuilding',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='typeservice',
            options={'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
        migrations.AlterField(
            model_name='denyroom',
            name='food',
            field=models.CharField(choices=[('food1', 'Первый тип питания'), ('food2', 'Второй тип питания'), ('food3', 'Третий тип питания')], default='food1', max_length=9),
        ),
        migrations.AlterField(
            model_name='departurecustomer',
            name='food',
            field=models.CharField(choices=[('food1', 'Первый тип питания'), ('food2', 'Второй тип питания'), ('food3', 'Третий тип питания')], default='food1', max_length=9),
        ),
        migrations.AlterField(
            model_name='entrycustomer',
            name='food',
            field=models.CharField(choices=[('food1', 'Первый тип питания'), ('food2', 'Второй тип питания'), ('food3', 'Третий тип питания')], default='food1', max_length=9),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
