# Generated by Django 4.2.1 on 2023-06-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_client_options_alter_denyroom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='denyroom',
            options={'verbose_name': 'отказ клиента', 'verbose_name_plural': 'Отказы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='departurecustomer',
            options={'verbose_name': 'выезд клиента', 'verbose_name_plural': 'Выезды клиентов'},
        ),
        migrations.AlterModelOptions(
            name='entrycustomer',
            options={'verbose_name': 'заезд клиента', 'verbose_name_plural': 'Заезды клиентов'},
        ),
        migrations.AlterModelOptions(
            name='hotelbuilding',
            options={'verbose_name': 'корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'комнату', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='typeservice',
            options={'verbose_name': 'тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default=1, upload_to='./staff'),
            preserve_default=False,
        ),
    ]
